<?php
	$variable1 = '123abc';
	$variable2 = null;
	$variable3 ='';
	$variable4 = 'abc123';
    $variable5 = 'null';
//(int)$variable1;
//(float)$variable1;
//(string)$variable1;
//(boolean)$variable1;
//(int)$variable2;
//(float)$variable2;
//(string)$variable2;
//(boolean)$variable2;
//(int)$variable3;
//(float)$variable3;
//(string)$variable3;
//(boolean)$variable3;
//(int)$variable4;
//(float)$variable4;
//(string)$variable4;
//(boolean)$variable4;
//(int)$variable5;
//(float)$variable5;
//(string)$variable5;
//(boolean)$variable5;
echo'Biến $variable1 sau khi ép sang int có giá trị = '.(int)$variable1;
echo"<br/>";
echo'Biến $variable1 sau khi ép sang float có giá trị = '.(float)$variable1;
echo"<br/>";
echo'Biến $variable1 sau khi ép sang string có giá trị = '.(string)$variable1;
echo"<br/>";
echo'Biến $variable1 sau khi ép sang boolean có giá trị = '.(boolean)$variable1;
echo"<br/>";
echo'Biến $variable2 sau khi ép sang int có giá trị = '.(int)$variable2;
echo"<br/>";
echo'Biến $variable2 sau khi ép sang float có giá trị = '.(float)$variable2;
echo"<br/>";
echo'Biến $variable2 sau khi ép sang string có giá trị = '.(string)$variable2;
echo"<br/>";
echo'Biến $variable2 sau khi ép sang boolean có giá trị = '.(boolean)$variable2;
echo"<br/>";
echo'Biến $variable3 sau khi ép sang int có giá trị = '.(int)$variable3;
echo"<br/>";
echo'Biến $variable3 sau khi ép sang float có giá trị = '.(float)$variable3;
echo"<br/>";
echo'Biến $variable3 sau khi ép sang string có giá trị = '.(string)$variable3;
echo"<br/>";
echo'Biến $variable3 sau khi ép sang boolean có giá trị = '.(boolean)$variable3;
echo"<br/>";
echo'Biến $variable4 sau khi ép sang int có giá trị = '.(int)$variable4;
echo"<br/>";
echo'Biến $variable4 sau khi ép sang float có giá trị = '.(float)$variable4;
echo"<br/>";
echo'Biến $variable4 sau khi ép sang string có giá trị = '.(string)$variable4;
echo"<br/>";
echo'Biến $variable4 sau khi ép sang boolean có giá trị = '.(boolean)$variable4;
echo"<br/>";
echo'Biến $variable5 sau khi ép sang int có giá trị = '.(int)$variable5;
echo"<br/>";
echo'Biến $variable5 sau khi ép sang float có giá trị = '.(float)$variable5;
echo"<br/>";
echo'Biến $variable5 sau khi ép sang string có giá trị = '.(string)$variable5;
echo"<br/>";
echo'Biến $variable5 sau khi ép sang boolean có giá trị = '.(boolean)$variable5;
echo"<br/>";
?>